import { jsPDF } from 'jspdf';

export async function exportProgressPdf(profile, rewards, progressRecords, notes) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text('NeighBright Progress Report', 20, 20);

  doc.setFontSize(12);
  doc.text(`Child: ${profile.name}`, 20, 35);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 42);
  doc.text(`Tier: ${profile.tier}`, 20, 49);

  // Summary stats
  doc.setFontSize(14);
  doc.text('Summary', 20, 65);
  doc.setFontSize(11);
  doc.text(`Total Stars: ${rewards.totalStars || 0}`, 25, 75);
  doc.text(`Current Streak: ${rewards.currentStreak || 0} days`, 25, 82);
  doc.text(`Longest Streak: ${rewards.longestStreak || 0} days`, 25, 89);

  // Total practice time
  const totalSecs = progressRecords.reduce((sum, r) => sum + (r.durationSecs || 0), 0);
  const hours = Math.floor(totalSecs / 3600);
  const mins = Math.floor((totalSecs % 3600) / 60);
  doc.text(`Total Practice Time: ${hours}h ${mins}m`, 25, 96);

  // Module breakdown
  const modules = {};
  progressRecords.forEach(r => {
    modules[r.module] = (modules[r.module] || 0) + 1;
  });

  let y = 113;
  doc.setFontSize(14);
  doc.text('Activity by Module', 20, y);
  y += 10;
  doc.setFontSize(11);
  Object.entries(modules).forEach(([mod, count]) => {
    doc.text(`${mod}: ${count} activities`, 25, y);
    y += 7;
  });

  // Session notes (last 10)
  if (notes && notes.length > 0) {
    y += 10;
    doc.setFontSize(14);
    doc.text('Recent Session Notes', 20, y);
    y += 10;
    doc.setFontSize(10);
    notes.slice(0, 10).forEach(note => {
      const date = new Date(note.createdAt).toLocaleDateString();
      const text = `[${date}] ${note.noteText}`;
      const lines = doc.splitTextToSize(text, 170);
      lines.forEach(line => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 25, y);
        y += 6;
      });
      y += 2;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.text('Generated by NeighBright — Free Speech Therapy App', 20, 285);

  doc.save(`neighbright-progress-${profile.name}-${new Date().toISOString().split('T')[0]}.pdf`);
}
